Integrates driver framework
ZigEmbeddedGroup/microzig pull request #246
Opened 2024-10-07 18:28 UTC by ikskuh

2024-10-07 19:55 UTC, mattnite requested changes
Looks good, just some cleanup needed.

2024-10-07 19:55 UTC, mattnite commented on driver/base/DatagramDevice.zig
> +object: ?*anyopaque,
please put struct members at the top of the file, it's difficult to find them in this sea of text

2024-10-07 19:55 UTC, mattnite commented on driver/base/DatagramDevice.zig
> +    fn connectFn(ctx: ?*anyopaque) ConnectError!void {
🐍

2024-10-07 19:55 UTC, mattnite commented on driver/base/DatagramDevice.zig
> +    fn disconnectFn(ctx: ?*anyopaque) void {
🐍

2024-10-07 19:55 UTC, mattnite commented on driver/base/DatagramDevice.zig
> +    fn writeFn(ctx: ?*anyopaque, datagram: []const u8) WriteError!void {
🐍

2024-10-07 19:55 UTC, mattnite commented on driver/base/DatagramDevice.zig
> +    fn readFn(ctx: ?*anyopaque, datagram: []u8) ReadError!void {
🐍

2024-10-07 19:55 UTC, mattnite commented on driver/base/DatagramDevice.zig
> +    connectFn: ?*const fn (?*anyopaque) ConnectError!void,
🐍

2024-10-07 19:55 UTC, mattnite commented on driver/base/DigitalIO.zig
> +const DigitalIO = @This();
Shouldn't this be `Digital_IO`?

2024-10-07 19:55 UTC, mattnite commented on driver/display/colors.zig
> +fn makeDefaultColors(comptime Color: type) type {
🐍

2024-10-07 19:55 UTC, mattnite commented on driver/display/ili9488.zig
> +//! TODO: Implement driver for ILI9488
Please don't create empty TODO files, make a ticket instead.

2024-10-07 19:55 UTC, mattnite commented on driver/display/ssd1306.zig
> +test "setContrast" {
I think this file would be a great candidate for symbol tests. If not, then please rename the tests to match the snake case function names.

2024-10-07 19:55 UTC, mattnite commented on driver/framework.zig
> +//!
empty doc comment

2024-10-07 19:55 UTC, mattnite commented on driver/input/touch/xpt2046.zig
> +//! TODO: Implement XPT2046 driver
Please delete empty TODO file, create ticket instead.

2024-10-07 19:55 UTC, mattnite commented on driver/wireless/sx1278.zig
> +//! TODO: Implement driver for SX1278
Please delete empty TODO file, create ticket instead.

2024-10-08 11:38 UTC, ikskuh commented on driver/display/ili9488.zig
> +//! TODO: Implement driver for ILI9488
https://github.com/ZigEmbeddedGroup/microzig/issues/249

2024-10-08 11:38 UTC, ikskuh commented on driver/wireless/sx1278.zig
> +//! TODO: Implement driver for SX1278
https://github.com/ZigEmbeddedGroup/microzig/issues/248

2024-10-08 11:38 UTC, ikskuh commented on driver/input/touch/xpt2046.zig
> +//! TODO: Implement XPT2046 driver
https://github.com/ZigEmbeddedGroup/microzig/issues/247

2024-10-08 11:39 UTC, ikskuh commented
Did a pretty extensive clean-up, changed the pattern a bit to use comptime options structs, which are more flexible, more uniform and also more convenient in the end.

Also applied more :snake: to the code

2024-11-14 15:38 UTC, merged