RP2 writev/readv implementation
ZigEmbeddedGroup/microzig pull request #254
Opened 2024-10-09 09:31 UTC by ikskuh

I've started implementing the writev/readv parts of the code and did some chores to clean up the code on the go

Not mergable yet as SPI devices are missing. Will add them and do some more cleanups before we're ready to merge

2024-10-09 16:45 UTC, haydenridd approved these changes
Looks great to me! Appreciate some of the cleanup surrounding repeated code in I2C :)

2024-10-09 21:16 UTC, haydenridd requested changes
Just ran it on my hardware needed to change those two things to get it to compile. Runs fine though with my existing "self test" routines though so good to go after that!

2024-10-09 21:16 UTC, haydenridd commented on port/raspberrypi/rp2xxx/src/hal/i2c.zig
> +        if (write_vec.len() == 0)
Needs to be `size()`!

2024-10-09 21:16 UTC, haydenridd commented on port/raspberrypi/rp2xxx/src/hal/i2c.zig
> +        if (write_vec.len() == 0)
Also needs to be `size()`!

2024-10-09 21:56 UTC, haydenridd approved these changes
Sweet, worked like a charm!

2024-10-10 02:26 UTC, mattnite approved these changes

2024-10-10 02:26 UTC, mattnite commented
Looks great @ikskuh ! love the deadlines

2024-10-10 15:45 UTC, merged