Register Map Implementation for Cortex M33
ZigEmbeddedGroup/microzig pull request #257
Opened 2024-10-14 23:14 UTC by Dolphindalt

Provides a minimal implementation of `core/src/cpus/cortex_m/m33.zig` derived from the [official documentation](https://www.st.com/resource/en/programming_manual/pm0264-stm32-cortexm33-mcus-programming-manual-stmicroelectronics.pdf).

2024-10-16 18:19 UTC, ikskuh commented
Can you add a link to the documentation into the file? That would help maintainers quickly find the docs if they need to touch that code :)

2024-10-20 13:37 UTC, mattnite requested changes

2024-10-20 13:37 UTC, mattnite commented on core/src/cpus/cortex_m/m33.zig
> +    pub const RBAR = mmio.Mmio(packed struct(u32) {
Please add doc comments to fields

2024-10-20 13:37 UTC, mattnite commented on core/src/cpus/cortex_m/m33.zig
> +    pub const RLAR = mmio.Mmio(packed struct(u32) {
Please add doc comments to fields

2024-10-26 16:39 UTC, mattnite approved these changes
Thank you!

2024-10-26 16:40 UTC, merged