Port for WCH CH32V series (CH32V003, CH32V103, and CH32V203)
ZigEmbeddedGroup/microzig pull request #286
Opened 2024-11-13 21:44 UTC by nosuz

I have added port modules and examples for WCH CH32V serires MPU.
Examples programs can be built by `make` in examples/wch.

I am happy to be merged my work.

However, I have found the other Pull-Request [#223](https://github.com/ZigEmbeddedGroup/microzig/pull/223) which supports CH32V003 is proposed. Should I merge this Pull-Request int my branch?

Thank you,

2024-11-14 13:04 UTC, ikskuh requested changes
This review was just a quick structural review, but it looks like you've made big progress on WCH front, which is great!

Will take a closer look if i find the time

2024-11-14 13:04 UTC, ikskuh commented on examples/wch/ch32v003/Makefile
Same as with the other Makefile

2024-11-14 13:04 UTC, ikskuh commented on examples/wch/ch32v103/LICENSE
Please delete this file, we don't need a copyright per port

2024-11-14 13:04 UTC, ikskuh commented on examples/wch/ch32v103/Makefile
See other Makefile comments

2024-11-14 13:04 UTC, ikskuh commented on examples/wch/ch32v203/LICENSE
Please delete this file, we don't need a copyright per port

2024-11-14 13:04 UTC, ikskuh commented on examples/wch/ch32v203/Makefile
See other Makefiles

2024-11-14 13:04 UTC, ikskuh commented on port/wch/ch32v/LICENSE
Please delete this file, we don't need a copyright per port

2024-11-14 13:04 UTC, ikskuh commented on port/wch/ch32v/src/chips/ch32v003.zig
Please do not check in the register files generated by regz. You can directly use the `svd` files as register definitions.

2024-11-14 13:04 UTC, ikskuh commented on port/wch/ch32v/src/chips/ch32v103.zig
Please do not check in the register files generated by regz. You can directly use the `svd` files as register definitions.

2024-11-14 13:04 UTC, ikskuh commented on port/wch/ch32v/src/chips/ch32v103xx.zig
Please do not check in the register files generated by regz. You can directly use the `svd` files as register definitions.

2024-11-14 13:04 UTC, ikskuh commented on port/wch/ch32v/src/chips/ch32v20x.zig
Please do not check in the register files generated by regz. You can directly use the `svd` files as register definitions.

2024-11-15 01:01 UTC, nosuz commented on examples/wch/Makefile
Thank you for reviewing my Pull-Request.
I think I have followed your all suggestions.

I removed the Makefiles and moved all examples into ch32v directory.

2024-11-15 01:02 UTC, nosuz commented on examples/wch/ch32v003/LICENSE
I have removed the LICENSE files from exsample directorys.

2024-11-15 01:02 UTC, nosuz commented on examples/wch/ch32v003/Makefile
I have removed the Makefile.

2024-11-15 01:03 UTC, nosuz commented on examples/wch/ch32v103/Makefile
I have removed the Makefile.

2024-11-15 01:03 UTC, nosuz commented on examples/wch/ch32v103/LICENSE
I have removed the LICENSE file.

2024-11-15 01:03 UTC, nosuz commented on examples/wch/ch32v203/LICENSE
I have removed the LICENSE file.

2024-11-15 01:03 UTC, nosuz commented on examples/wch/ch32v203/Makefile
I have removed the Makefile.

2024-11-15 01:04 UTC, nosuz commented on port/wch/ch32v/LICENSE
I have removed the LICENSE file.

2024-11-15 01:05 UTC, nosuz commented on port/wch/ch32v/src/chips/ch32v103.zig
I removed the register file generated by regz.

2024-11-15 01:05 UTC, nosuz commented on port/wch/ch32v/src/chips/ch32v103xx.zig
I removed the register file generated by regz.

2024-11-15 01:06 UTC, nosuz commented on port/wch/ch32v/src/chips/ch32v20x.zig
I removed the register file generated by regz.

Thank you,

2024-11-15 20:44 UTC, nosuz commented
Thank you for your kindly revew and sugestions.
I have followed your all suggestions and updated my branch to integrate the chages in your main branch.

2024-11-22 00:00 UTC, nosuz commented
@mattnite Thank you for your advice. I have rebased to your current main branch. And I have also changed build.zig files in the top and examples directories to add "wch/ch32".

2024-11-22 00:07 UTC, mattnite commented
@nosuz thank you!

2024-11-22 00:07 UTC, mattnite approved these changes

2024-11-22 00:08 UTC, merged

2024-11-22 00:34 UTC, nosuz commented
@mattnite Thank you very much for merging my Pull-Request.

But I am sorry I found my examples fail to compile becase of the chnage by "Build system rewrite" [#259](https://github.com/ZigEmbeddedGroup/microzig/pull/259). I am going to fix.

Should I mention in this Pull-Request tree when I finished my work, or should I create new Pull-Request?

2024-11-22 00:38 UTC, mattnite commented
@nosuz No worries! I realized this may be the case. There's a few other issues that need fixing before the next release. I wanted to get all your good work in now, and then fix it up later when I had a couple patterns figured out for CI.

2024-11-23 06:49 UTC, nosuz commented
@mattnite Thank you for your advices. I am trying to fix this problem and will send a new PR when it is finished.