Add cortex m7 register definitions
ZigEmbeddedGroup/microzig pull request #294
Opened 2024-11-24 18:08 UTC by devBoi76

This PR adds some basic cortex-m7 register definitions.

I verified that ITM, TPIU, and DBG work on an STM32f746ng-disco board with this sample code to write debug info through SWD:

```zig
const std = @import("std");
const microzig = @import("microzig");
const stm32 = microzig.hal;
const cpu = microzig.cpu;

pub fn initSWO() void {
    // Enable trace in core debug:
    cpu.dbg.DEMCR.modify(.{ .TRCENA = 1 }); // Enable debugging & monitoring

    // Enable ITM:
    cpu.itm.TCR.modify(.{
        .ITMENA = 1, // Enable ITM
        .SYNCENA = 1, // Enabe sync packets
        .TXENA = 1, // Enable DWT packets
        .TraceBusID = 1, // Unique ID for multi-source trace
    });

    // Enable stimulus port 0:
    cpu.itm.TER[0].modify(.{ .STIMENA = 1 });

    // Configure Serial Wire Output (SWO):
    cpu.tpiu.SPPR.modify(.{ .TXMODE = 0b10 }); // NZ mode
    cpu.tpiu.ACPR.modify(.{ .SWOSCALER = 7 }); // Set prescaler (for 2MHz output @16MHz)

}

// Helper function to write a byte to ITM stimulus port
pub fn writeITM(ch: u8) void {
    // Wait until stimulus port is ready
    while (cpu.itm.STIM[0].read().READ.FIFOREADY == 0) {}

    // Write character
    // cpu.itm.STIM[0].write(.{ .WRITE_U8 = ch });
    const stim: *volatile u8 = @ptrCast(&cpu.itm.STIM[0].raw);
    stim.* = ch;
}

pub fn writeBytes(str: []const u8) void {
    for (str) |ch| {
        writeITM(ch);
    }
}

pub fn main() void {
    initSWO();
    var fmt_buf: [1024]u8 = undefined;
    var i: u32 = 0;
    while (true) : (i += 1) {
        writeBytes(std.fmt.bufPrintZ(&fmt_buf, "({d}) Hello, SWD!\n", .{i}) catch {
            writeBytes("Buf print formatting error!\n");
            continue;
        });

        for (0..10_000) |_| {
            asm volatile ("nop");
        }
    }
}
```

Prints out what you would expect.

2024-11-25 07:57 UTC, mattnite requested changes

2024-11-25 07:57 UTC, mattnite commented on core/src/cpus/cortex_m/m7_utils.zig
> +pub fn initSWO(config: struct {
`init_swo`

2024-11-25 07:57 UTC, mattnite commented on core/src/cpus/cortex_m/m7_utils.zig
> +pub fn writeByteITM(ch: u8, stim_port: u5) void {
`write_byte_itm`

2024-11-25 07:57 UTC, mattnite commented on core/src/cpus/cortex_m/m7_utils.zig
> +pub fn writeBytesITM(str: []const u8, stim_port: u5) void {
`write_bytes_itm`

2024-11-25 11:35 UTC, devBoi76 commented on core/src/cpus/cortex_m/m7_utils.zig
> +pub fn writeBytesITM(str: []const u8, stim_port: u5) void {
Done

2024-11-26 19:34 UTC, mattnite approved these changes

2024-11-26 23:13 UTC, mattnite commented
@devBoi76 please fix the conflicts and then we're ready to merge

2024-11-27 10:29 UTC, devBoi76 commented
@mattnite Done 👍

2024-11-29 08:51 UTC, merged