add hd44780 driver + rppico example
ZigEmbeddedGroup/microzig pull request #301
Opened 2024-11-30 19:26 UTC by RecursiveError

2024-12-02 21:07 UTC, mattnite requested changes
Looks good, just needs style fixes

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn shift_cursor_left(Self: *HD44780) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn shift_cursor_right(Self: *HD44780) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn shift_display_left(Self: *HD44780) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn shift_display_right(Self: *HD44780) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn shift_control(Self: *HD44780, st: State) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn shift_mode(Self: *HD44780, mode: ShiftDirection) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn display_set(Self: *HD44780, st: State) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn cursor_control(Self: *HD44780, st: State) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn cursor_blink_control(Self: *HD44780, st: State) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn select_all(Self: *HD44780) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub inline fn select_lcd(Self: *HD44780, en: u1) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn set_cursor(Self: *HD44780, line: u8, col: u8) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn create_custom_char(Self: *HD44780, new_char: [8]u8, mem_addr: u8) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn write(Self: *HD44780, text: []const u8) *HD44780 {
see above

2024-12-02 21:07 UTC, mattnite commented on drivers/display/hd44780.zig
> +    pub fn init_device(Self: *HD44780, skip_init_time: bool) *HD44780 {
see above

2024-12-02 21:37 UTC, ikskuh requested changes
Overall it looks pretty good, but i'd remove the explicit type from `enum(u8)` if we don't require a u8 here. We can just use `enum { }` for enums that provide selective options

2024-12-02 21:37 UTC, ikskuh commented on drivers/display/hd44780.zig
> +    io_interface: mdf.base.Datagram_Device,
This struct should follow the others, and have a `HD44780_Config` type which configures the `HD44780` struct. As you're using `Datagram_Device`, you should do something like
```zig
const HD44780_Config = struct {
  Datagram_Device: type = mdf.base.Datagram_Device,
};

pub fn HD44780(comptime config: HD44780_Config) type {
    return struct {
         …
         io_interface: config.Datagram_Device,
         …
    };
}
```
This way, you can either use the runtime dispatch variant with `HD44780(.{})` or you can replace the runtime dispatch with an arbitrary different dispatcher like a TestDevice or a concrete, non-vtable implementation

2024-12-02 21:37 UTC, ikskuh commented on examples/raspberrypi/rp2xxx/src/rp2040_only/hd44780.zig
> +};
We do have a ready-to-use implementation in https://github.com/ZigEmbeddedGroup/microzig/blob/dad43d5f9bad5bf8082dd2425c469e323f2066d7/port/raspberrypi/rp2xxx/src/hal/drivers.zig#L18-L34

2024-12-04 17:05 UTC, mattnite requested changes

2024-12-04 17:05 UTC, mattnite commented on drivers/display/hd44780.zig
> +pub const LcdCommands = enum(u8) {
`LCD_Commands`

2024-12-07 16:53 UTC, mattnite approved these changes

2024-12-07 17:37 UTC, merged